
services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-dock
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4

  config-service:
    build: ./config-service
    container_name: config-dock
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
    depends_on:
      discovery-service:
        condition: service_healthy

  utilisateur-service:
    build: ./utilisateur-service
    container_name: utilisateur-dock
    ports:
      - '9094:9094'
    expose:
      - '9094'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9094/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
    depends_on:
      config-service:
        condition: service_healthy

  livre-service:
    build: ./livre-service
    container_name: livre-dock
    ports:
      - '9091:9091'
    expose:
      - '9091'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
    depends_on:
      config-service:
        condition: service_healthy

  emprunt-service:
    build: ./emprunt-service
    container_name: emprunt-dock
    ports:
      - '9093:9093'
    expose:
      - '9093'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9093/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
    depends_on:
      config-service:
        condition: service_healthy
      utilisateur-service:
        condition: service_healthy
      livre-service:
        condition: service_healthy

  gateway-service:
    build: ./gateway-service
    container_name: gateway-dock
    ports:
      - '8888:8888'
    expose:
      - '8888'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:9999
    depends_on:
      emprunt-service:
        condition: service_healthy
  front-angular:
    image: front_angular
    container_name: front-angular-dock
    ports:
      - '4200:80'
    expose:
      - '80'
    depends_on:
      gateway-service:
        condition: service_healthy